### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by sweeterzone** [hack-chat/3rd-party-software-list#10] opened 2019-08-28 15:13 UTC
Hi, how i can chage background color from black to white using url? Thanks in advance

**Comment by marzavec** [comment] 2019-08-29 13:35
Hi. Are you talking about a piece of software on this list?

**Comment by marzavec** [comment] 2019-09-04 16:16
Duplicate of https://github.com/hack-chat/main/issues/78 Closed

**Closed by marzavec** 2019-09-04 16:16 UTC
